FROM nginx:alpine

COPY web/landing/index.html /usr/share/nginx/html/index.html
COPY web/landing/cameras.html /usr/share/nginx/html/cameras.html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
